apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-bastion
  namespace: sflow-gw
  labels:
    app: sshd-bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd-bastion
  template:
    metadata:
      labels:
        app: sshd-bastion
    spec:
      serviceAccountName: slflow-sa
      containers:
        - name: udplistener
          image: "quay.io/abranzyck/sshd-udplisten:test_rhel_ubi3"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 6343
              protocol: UDP
        - name: sshd
          image: "quay.io/abranzyck/sshd-bastion:rhel_ubi7"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 2222
              protocol: TCP
            - containerPort: 6343
              protocol: TCP
          env:
            - name: SSH_KEY
              valueFrom:
                secretKeyRef:
                  name: sshd-bastion-secret
                  key: SSH_KEY
