apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-bastion
  namespace: test-gw
  labels:
    app: sshd-bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd-bastion
  template:
    metadata:
      labels:
        app: sshd-bastion
    spec:
      containers:
        - name: sshd
          image: "default-route-openshift-image-registry.apps-crc.testing/test-gw/sshd-bastion:latest"
          ports:
            - containerPort: 22
              protocol: TCP
            - containerPort: 6343
              protocol: UDP
          env:
            - name: SSH_KEY
              valueFrom:
                secretKeyRef:
                  name: sshd-bastion-secret
                  key: SSH_KEY
