apiVersion: v1
kind: Service
metadata:
  name: sshd-bastion-service
  namespace: sflow-gw
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
    service.kubernetes.io/ibm-load-balancer-cloud-provider-vpc-health-check-udp: "10250"
spec:
  selector:
    app: sshd-bastion
  type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 2222
    - name: sflow
      protocol: UDP
      port: 6343
      targetPort: 6343

