apiVersion: v1
kind: Service
metadata:
  name: sshd-bastion-service
  namespace: bastion
spec:
  selector:
    app: sshd-bastion
  type: NodePort
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
      nodePort: 2222
   - name: sflow
      protocol: UDP
      port: 6343
      targetPort: 6343
      nodePort: 6343
